/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;


public class frmEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        // Generated using JFormDesigner Evaluation license - Jesber Nair Quinto Cordoba
        private void initComponents() {
            jMenuBar1 = new JMenuBar();
            jMenu1 = new JMenu();
            jMenu2 = new JMenu();
            jMenu3 = new JMenu();
            jMenu4 = new JMenu();
            jMenu5 = new JMenu();
            jMenu6 = new JMenu();
            nid = new JTextField();
            jComboBox1 = new JComboBox<>();
            jComboBox2 = new JComboBox<>();
            nombre = new JTextField();
            apellido = new JTextField();
            jLabel1 = new JLabel();
            jLabel2 = new JLabel();
            jLabel3 = new JLabel();
            jLabel4 = new JLabel();
            jLabel5 = new JLabel();
            jLabel6 = new JLabel();
            txtfecNac = new JTextField();

            //======== this ========
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            var contentPane = getContentPane();

            //======== jMenuBar1 ========
            {

                //======== jMenu1 ========
                {
                    jMenu1.setText("Nuevo");
                    jMenu1.addActionListener(e -> jMenu1ActionPerformed(e));
                }
                jMenuBar1.add(jMenu1);

                //======== jMenu2 ========
                {
                    jMenu2.setText("Guardar");
                }
                jMenuBar1.add(jMenu2);

                //======== jMenu3 ========
                {
                    jMenu3.setText("Consultar");
                }
                jMenuBar1.add(jMenu3);

                //======== jMenu4 ========
                {
                    jMenu4.setText("Modificar");
                }
                jMenuBar1.add(jMenu4);

                //======== jMenu5 ========
                {
                    jMenu5.setText("Eliminar");
                }
                jMenuBar1.add(jMenu5);

                //======== jMenu6 ========
                {
                    jMenu6.setText("Salir");
                }
                jMenuBar1.add(jMenu6);
            }
            setJMenuBar(jMenuBar1);

            //---- nid ----
            nid.addActionListener(e -> nidActionPerformed(e));

            //---- jComboBox1 ----
            jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] {
                "Item 1",
                "Item 2",
                "Item 3",
                "Item 4"
            }));
            jComboBox1.addActionListener(e -> jComboBox1ActionPerformed(e));

            //---- jComboBox2 ----
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] {
                "Item 1",
                "Item 2",
                "Item 3",
                "Item 4"
            }));

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 12));
            jLabel1.setText("No id");

            //---- jLabel2 ----
            jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 12));
            jLabel2.setText("Nombre");

            //---- jLabel3 ----
            jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 12));
            jLabel3.setText("Apellido");

            //---- jLabel4 ----
            jLabel4.setFont(new Font("Segoe UI", Font.BOLD, 12));
            jLabel4.setText("Genero");

            //---- jLabel5 ----
            jLabel5.setFont(new Font("Segoe UI", Font.BOLD, 12));
            jLabel5.setText("Cargo");

            //---- jLabel6 ----
            jLabel6.setFont(new Font("Segoe UI", Font.BOLD, 12));
            jLabel6.setText("Fecha de nacimiento");

            GroupLayout contentPaneLayout = new GroupLayout(contentPane);
            contentPane.setLayout(contentPaneLayout);
            contentPaneLayout.setHorizontalGroup(
                contentPaneLayout.createParallelGroup()
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contentPaneLayout.createParallelGroup()
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(contentPaneLayout.createParallelGroup()
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nombre, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(nid)
                                        .addComponent(apellido))
                                    .addComponent(jComboBox1, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtfecNac, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(106, Short.MAX_VALUE))
            );
            contentPaneLayout.setVerticalGroup(
                contentPaneLayout.createParallelGroup()
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(contentPaneLayout.createParallelGroup()
                            .addComponent(jLabel3, GroupLayout.Alignment.TRAILING)
                            .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(nid, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contentPaneLayout.createParallelGroup()
                            .addComponent(txtfecNac, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(contentPaneLayout.createParallelGroup()
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contentPaneLayout.createParallelGroup()
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))
            );
            pack();
            setLocationRelativeTo(getOwner());
        }// </editor-fold>//GEN-END:initComponents

    private void nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nidActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

        private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmpleado().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        // Generated using JFormDesigner Evaluation license - Jesber Nair Quinto Cordoba
        private JMenuBar jMenuBar1;
        private JMenu jMenu1;
        private JMenu jMenu2;
        private JMenu jMenu3;
        private JMenu jMenu4;
        private JMenu jMenu5;
        private JMenu jMenu6;
        private JTextField nid;
        private JComboBox<String> jComboBox1;
        private JComboBox<String> jComboBox2;
        private JTextField nombre;
        private JTextField apellido;
        private JLabel jLabel1;
        private JLabel jLabel2;
        private JLabel jLabel3;
        private JLabel jLabel4;
        private JLabel jLabel5;
        private JLabel jLabel6;
        private JTextField txtfecNac;
        // End of variables declaration//GEN-END:variables
}
